export enum MODE_ENUM {
  PUBLIC = "PUBLIC",
  PRIVE = "PRIVE",
}

export enum ROLE_ENUM {
  COMMUN = "COMMUN",
  PARTENAIRE = "PARTENAIRE",
}

export enum STATUS_ENUM {
  CARTOGRAPHIQUE = "CARTOGRAPHIQUE",
  REEL = "REEL",
}

export enum CHAT_ENUM {
  RETRO = "RETRO",
  MODERNE = "MODERNE",
}

export enum TYPE_CLEF_ENUM {
  DECOUVERTE = "DECOUVERTE",
  PASSPHRASE = "PASSPHRASE",
  REPERE = "REPERE",
}

export enum TYPE_RECOMPENSE_ENUM {
  COURONNE = "COURONNE",
  CARTE_COLLECTION = "CARTE_COLLECTION",
  EXTERNE = "EXTERNE",
}
